FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    nmap \
    iproute2 \
    util-linux \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm ci

COPY . .

USER 65534:65534
CMD ["npm", "run", "dev:worker"]
